---
title: 'Cyberville Dataset Description'
output:
  html_document:
    theme: united
    toc: true
    toc_float: true
css: laurens_styles.css
---

```{r, child="_Global-Options.Rmd"}
```
***
***
### families.csv

```{r}
tempData <- read.csv(url("https://laurencipriano.github.io/IveyBusinessStatistics/Datasets/families.csv"), header = TRUE)

summary(tempData)
```

The data set families contains information about 43,886 families living in the city of Cyberville. The city has four regions. In these exercises, we will learn about the families of Cyberville by using sampling. For each family, the following information is recorded:

```{r, echo=FALSE}
# Create the dataframe for family-related variables
family_variables <- data.frame(
  Variable = c("Family type", "*1: Husband-wife family*", "*2: Male-head family*", "*3: Female-head family*",
               "Number of persons in family", "Number of children in family", "Family income", 
               "Region", "*1: North*", "*2: East*", "*3: South*", "*4: West*",
               "Education", "*31: Less than 1st grade*", "*32: 1st, 2nd, 3rd, or 4th grade*", "*33: 5th or 6th grade*", 
               "*34: 7th or 8th grade*", "*35: 9th grade*", "*36: 10th grade*", "*37: 11th grade*", "*38: 12th grade, no diploma*", 
               "*39: High school graduate*", "*40: Some college but no degree*", "*41: Associate degree in college (occupation/vocation program)*", 
               "*42: Associate degree in college (academic program)*", "*43: Bachelor’s degree*", "*44: Master’s degree*", 
               "*45: Professional school degree*", "*46: Doctoral degree*"),
  Description = c("Family type", "*Husband-wife family*", "*Male-head family*", "*Female-head family*",
                  "Total number of persons in the family", "Total number of children in the family", "*Family income (numeric)*", 
                  "Region where the family resides", "*North region with 10,149 families*", "*East region with 10,390 families*", 
                  "*South region with 13,457 families*", "*West region with 9,890 families*", 
                  "Education level", "*Less than 1st grade*", "*1st, 2nd, 3rd, or 4th grade*", "*5th or 6th grade*", 
                  "*7th or 8th grade*", "*9th grade*", "*10th grade*", "*11th grade*", "*12th grade, no diploma*", 
                  "*High school graduate, high school diploma, or equivalent*", "*Some college but no degree*", 
                  "*Associate degree in college (occupation/vocation program)*", "*Associate degree in college (academic program)*", 
                  "*Bachelor’s degree (e.g., B.S., B.A., A.B.)*", "*Master’s degree (e.g., M.S., M.A., M.B.A.)*", 
                  "*Professional school degree (e.g., M.D., D.D.S., D.V.M., LL.B., J.D.)*", "*Doctoral degree (e.g. Ph.D., Ed.D.)*")
)

# Render the table in R Markdown
kable(family_variables, caption = "List of Family Variables and Definitions")
```
    
    
