---
title: "GSS_Happy Data Description"
output:
  html_document:
    theme: united
    toc: true
    toc_float: true
css: laurens_styles.css
---

```{r, child="_Global-Options.Rmd"}
```
***
***
### Occupational Prestige Data
```{r, eval=FALSE}
tempData <- read.csv(url("https://laurencipriano.github.io/IveyBusinessStatistics/Datasets/GSS_HappyData.csv"), header = TRUE)

#Not run due to large size of data
summary(tempData)
```

```{r, echo=FALSE}
# Create the individual dataframes for each section with the variable name removed from descriptions
survey_variables <- data.frame(
  Variable = c("**YEAR**", "**ID**", "**WEIGHT**"),
  Description = c("Year for this respondent", "Unique ID", "Combined survey weight variables: WTSSCOMP*OVERSAMP")
)

respondent_variables <- data.frame(
  Variable = c("**VHAPPY**", "**COHORT**", "**AGE**", "**SEX**", "**RACE**",
               "**DEGREE**", "**EDUC**", "**CLASS_**", "**HEALTH**", "**MARITAL**",
               "**DIVORCE**", "**CHILDS**"),
  Description = c("Respondent’s general happiness **1:** Very Happy **0:** Pretty Happy or Not too happy",
                  "Respondent's year of birth", "Age of Respondent", "Respondent's sex", "Race of respondent",
                  "Respondent’s highest degree", "Highest year of school completed (0=no formal education)",
                  "Self-identified social class (lower, working, middle, upper)", "Respondent’s self-identified health status",
                  "Marital status", "Ever divorced or separated", "Number of children")
)

respondent_home_variables <- data.frame(
  Variable = c("**REGION**", "**SIZE**", "**SRCBELT**", "**XNORCSIZ**",
               "**HHTYPE1**", "**HOMPOP**", "**ADULTS**", "**BABIES**", "**PRETEEN**",
               "**TEENS**", "**KidsAtHome**", "**HappyPartner**"),
  Description = c("Region where the interview took place", "Size of place (city or town where respondent lives) in 1000s",
                  "Location (Large Standard Metropolitan Statistical Area (SMSAs) Suburb of Large SMSA; Smaller SMSA; etc.)",
                  "Detailed location size (City/Suburb/Rural and population size)", "Household composition (Married no kids, Married with kids, etc.)",
                  "Number of persons in household", "Number of adults (people over 18 years) in household", "Household members less than 6 yrs old",
                  "Household members 6 thru 12 yrs old", "Household members 13 thru 17 yrs old", "Sum of BABIES, PRETEEN, & TEENS variables",
                  "Happiness of relationship with partner; Combination of happiness of relationship with GSS HAPCOHAB & HAPMAR variables")
)

work_and_income <- data.frame(
  Variable = c("**EARNRS**", "**WRKSTAT**", "**PRESTG10**", "**SEI10**",
               "**SPWRKSTA**", "**SPPRES10**", "**SPSEI10**", "**FINRELA**",
               "**SATFIN**", "**FINALTER**", "**SATJOB**", "**UNEMP**",
               "**JOBLOSE**", "**JobFind**", "**InflTarget**", "**InflNominal**",
               "**PersIncomeAdj**", "**FamIncomeAdj**", "**Z.Inc_Pers**", "**Z.Inc_Fam**",
               "**P.Inc_Pers**", "**P.Inc_Fam**"),
  Description = c("How many in family earn money?", "Labor force status", "Respondent’s occupational prestige score (0-100 scale)",
                  "Respondent’s socioeconomic index", "Spouse labor force status", "Spouse’s occupational prestige score (0-100 scale)",
                  "Spouse’s socioeconomic index", "Opinion of family income (above or below average)", "Satisfaction with current financial situation",
                  "Over the last few years, financial situation gotten better or worse?", "Overall satisfaction with work/role as home-maker",
                  "Ever unemployed in the last 10 years?", "Job security: Is respondent likely to lose their job?", "Job mobility: How hard would it be to find an equally good job?",
                  "Regional inflation index for 2023", "Regional inflation index for year of survey", "Estimated personal income adjusted for inflation Estimated income level, combining income brackets from eight different survey categorical definitions (RINCOME, RINCOM77, RINCOM82, RINCOM86, RINCOM91, RINCOM98, RINCOM06, RINCOM16) and then adjusted for inflation to 2023 real dollars.",
                  "Estimated family income adjusted for inflation. Estimated family income level, combining income brackets from nine different survey categorical definitions (INCOME72, INCOME, INCOME77, INCOME82, INCOME86, INCOME91, INCOME98, INCOME06, INCOME16) and then adjusted for inflation to 2023 real dollars.",
                  "Year-specific Z-score of personal income", "Year-specific Z-score of family income", "Year-specific percentile of personal income", "Year-specific percentile of family income")
)

social_activities <- data.frame(
  Variable = c("**SOCBAR**", "**SOCFREND**", "**SOCOMMUN**", "**SOCREL**",
               "**TVHOURS**"),
  Description = c("How often do you ... spend evening at a bar/tavern?", "How often do you ... spend an evening with friends?", "How often do you ... spend an evening with neighbour?",
                  "How often do you ... spend an evening with relatives?", "How many hours per day watching tv? (0-24 hours)")
)

political_and_religion <- data.frame(
  Variable = c("**POLVIEWS**", "**PARTYID**", "**RELIG**", "**RELITEN**",
               "**ATTEND**", "**FUND**"),
  Description = c("Self-identifies as liberal or conservative", "Political party affiliation", "Respondent’s religious preference",
                  "Strength of religious affiliation", "How often r attends religious services", "How fundamentalist is r currently?")
)

childhood_and_family_history <- data.frame(
  Variable = c("**BORN**", "**MomBornUS**", "**DadBornUS**", "**GRANBORN**",
               "**REG16**", "**RES16**", "**MOBILE16**", "**INCOM16**",
               "**MASEI10**", "**PASEI10**"),
  Description = c("Was respondent born in the USA", "Was r’s mother born in USA (1=yes, 2=no)", "Was r’s father born in USA (1=yes, 2=no)", "How many grandparents born outside the USA?",
                  "Region of residence, age 16", "Type of place lived in when 16 yrs old", "Geographic mobility since age 16", "r's family income when 16 yrs old", "r's mother's socioeconomic index", "r's father's socioeconomic index")
)

community_and_society <- data.frame(
  Variable = c("**TAX**", "**LIFE**", "**HELPFUL**"),
  Description = c("Do you consider the amount of federal income tax which you have to pay as too high, about right, or too low?",
                  "In general, do you find life exciting, pretty routine, or dull?", "Most of the time, are people helpful or looking out for themselves?")
)

confidence_in_social_institutions <- data.frame(
  Variable = c("**CONFINAN**", "**CONBUS**", "**CONCLERG**", "**CONEDUC**",
               "**CONFED**", "**CONLABOR**", "**CONPRESS**", "**CONMEDIC**",
               "**CONTV**", "**CONJUDGE**", "**CONSCI**", "**CONLEGIS**",
               "**CONARMY**"),
  Description = c("… banks and financial institutions", "… major companies", "… organized religion", "… education",
                  "… exec branch of fed govt", "… organized labor", "… press", "… medicine",
                  "… television", "… united states supreme court", "… scientific community", "… congress", "… military")
)

# Print the tables using kable
kable(survey_variables, format = "markdown", caption = "Survey Variables and Descriptions")

kable(respondent_variables, format = "markdown", caption = "Respondent Variables and Descriptions")

kable(respondent_home_variables, format = "markdown", caption = "Respondent Home Variables and Descriptions")

kable(work_and_income, format = "markdown", caption = "Work and Income Variables and Descriptions")

kable(social_activities, format = "markdown", caption = "Social Activities Variables and Descriptions")

kable(political_and_religion, format = "markdown", caption = "Political Ideology and Religion Variables and Descriptions")

kable(childhood_and_family_history, format = "markdown", caption = "Childhood and Family History Variables and Descriptions")

kable(community_and_society, format = "markdown", caption = "Feelings About Community and Society Variables and Descriptions")

kable(confidence_in_social_institutions, format = "markdown", caption = "Confidence in Social Institutions Variables and Descriptions")
```

