---
title: "MEPS Description"
output:
  html_document:
    theme: united
    toc: true
    toc_float: true
css: laurens_styles.css
---

```{r, child="_Global-Options.Rmd"}
```
***
***
### US Medical Expenditure Panel Survey (MEPS)
```{r}
tempData <- read.csv(url("https://laurencipriano.github.io/IveyBusinessStatistics/Datasets/mepsData.csv"), header = TRUE)

summary(tempData)
```

The data set mepsData is a longitudinal study which surveys and measures a particular group of people over time. In the case of MEPS, each household that is surveyed is surveyed a total of five times (or 5 interview rounds) over a period of two years.

```{r, echo=FALSE}
# Create the dataframe with variables and descriptions
health_data <- data.frame(
  Variable = c("**Person_ID**", "**Age**", "**Sex**", "**RaceEthnicity**", 
               "**CensusRegion**", "**HealthStatus**", "**MentalHealth**", 
               "**BMI**", "**HasHypertension**", "**HasDiabetes**", 
               "**Drinks5Day**", "**HealthInsurance**", "**HaveProvider**", 
               "**NotAffordHealthCare**", "**FamIncome_Continuous**", 
               "**FamIncome_PercentPoverty**", "**FamIncome_Categorical**", 
               "**TotalHealthExpenditure**"),
  Description = c("Unique ID", "In Years", 
                  "Self-Reported Gender **1:** Male **0:** Female", 
                  "Race/Ethnicity **1:** Hispanic **2:** Non-Hispanic White Only **3:** Non-Hispanic Black Only **4:** Non-Hispanic Asian Only **5:** Non-Hispanic Other Race or Multiple Race", 
                  "Respondents Census Region **1:** North-East **2:** Mid-West **3:** South **4:** West", 
                  "How does the respondent describe their own health **1:** Excellent **2:** Very Good **3:** Good **4:** Fair **5:** Poor", 
                  "How does the respondent describe their own mental health **1:** Excellent **2:** Very Good **3:** Good **4:** Fair **5:** Poor", 
                  "Body Mass Index (Collected for adults)", 
                  "Has the respondent been diagnosed with high blood pressure? **1:** Yes **0:** No", 
                  "Has the respondent been diagnosed with diabetes? **1:** Yes **0:** No", 
                  "Over the past 12 months, did the respondent have 5 or more alcoholic drinks per day? **1:** Yes **0:** No", 
                  "What type of health insurance, if any, does the respondent have? **1:** Any Private **2:** Public Only **3:** Uninsured", 
                  "Respondent has a usual healthcare provider **1:** Yes **0:** No", 
                  "In the past 12 months, respondent did not receive or delayed medical care because of cost? **1:** Yes **0:** No", 
                  "Family total income from all sources", 
                  "Family income divided by the applicable poverty line based on family size and composition", 
                  "Family income as a percent of the poverty line organized as a categorical variable **1:** Poor/Negative **2:** Near Poor **3:** Low Income **4:** Middle Income **5:** High Income", 
                  "Total health care expenditures ($): all sources (public insurance, private insurance, and out-of-pocket)")
)

# Display the table using kable
kable(health_data, format = "markdown", caption = "Health Data Variables and Descriptions")

```





    