---
title: "Occupational Prestige Data Description"
output:
  html_document:
    theme: united
    toc: true
    toc_float: true
css: laurens_styles.css
---

```{r, child="_Global-Options.Rmd"}
```
***
***
### Occupational Prestige Data
```{r}
tempData <- read.csv(url("https://laurencipriano.github.io/IveyBusinessStatistics/Datasets/PrestigeData.csv"), header = TRUE)

summary(tempData)
```

```{r, echo=FALSE}
# Survey Variables
survey_variables <- data.frame(
  Variable = c("**YEAR**", "**ID**"),
  Description = c("Year for this respondent", "Unique ID")
)

# Respondent Variables
respondent_variables <- data.frame(
  Variable = c("**AGE**", "**SEX**", "**DEGREE**", "**EDUC**", "**CLASS_**", "**MARITAL**"),
  Description = c("Age of Respondent", "Respondent's sex", "Respondent’s highest degree", 
                  "Highest year of school completed (0=no formal education)", 
                  "Self-identified social class (lower, working, middle, upper)", 
                  "Marital status")
)

# Respondent Home Variables
respondent_home_variables <- data.frame(
  Variable = c("**REGION**"),
  Description = c("Region where the interview took place")
)

# Work and Income Variables
work_and_income_variables <- data.frame(
  Variable = c("**PRESTG10**", "**SEI10**", "**FINRELA**", "**SATFIN**", "**UNEMP**", 
               "**JOBLOSE**", "**JobFind**", "**PersIncomeAdj**"),
  Description = c("Respondent’s occupational prestige score (0-100 scale)", 
                  "Respondent’s socioeconomic index", 
                  "Opinion of family income (above or below average)", 
                  "Satisfaction with current financial situation", 
                  "Ever unemployed in the last 10 years?", 
                  "Job security: Is respondent likely to lose their job?", 
                  "Job mobility: How hard would it be to find an equally good job?", 
                  "Estimated personal income adjusted for inflation. Estimated income level, combining income brackets from eight different survey categorical definitions (RINCOME, RINCOM77, RINCOM82, RINCOM86, RINCOM91, RINCOM98, RINCOM06, RINCOM16) and then adjusted for inflation to 2023 real dollars.")
)

# Childhood and Family History Variables
childhood_and_family_history_variables <- data.frame(
  Variable = c("**BORN**"),
  Description = c("Was respondent born in the USA")
)

kable(survey_variables, format = "markdown", caption = "Survey Variables")
kable(respondent_variables, format = "markdown", caption = "Respondent Variables")
kable(respondent_home_variables, format = "markdown", caption = "Respondent Home Variables")
kable(work_and_income_variables, format = "markdown", caption = "Work and Income Variables")
kable(childhood_and_family_history_variables, format = "markdown", caption = "Childhood and Family History Variables")

```

